// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhotoApp.Data;

#nullable disable

namespace PhotoApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251130130928_AddFilterOptionsTable")]
    partial class AddFilterOptionsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PhotoApp.Models.CustomUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PhotoApp.Models.FilterOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FilterOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Oprava"
                        },
                        new
                        {
                            Id = 2,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "AA Group"
                        },
                        new
                        {
                            Id = 3,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "AGC"
                        },
                        new
                        {
                            Id = 4,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Agor"
                        },
                        new
                        {
                            Id = 5,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Archeo"
                        },
                        new
                        {
                            Id = 6,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Vážeme"
                        },
                        new
                        {
                            Id = 7,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Badico"
                        },
                        new
                        {
                            Id = 8,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "BBH"
                        },
                        new
                        {
                            Id = 9,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Delasitas"
                        },
                        new
                        {
                            Id = 10,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Dijmex"
                        },
                        new
                        {
                            Id = 11,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Duo Pet"
                        },
                        new
                        {
                            Id = 12,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "JMK"
                        },
                        new
                        {
                            Id = 13,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Ecoprimus"
                        },
                        new
                        {
                            Id = 14,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "EF Recycling"
                        },
                        new
                        {
                            Id = 15,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Eri-trade"
                        },
                        new
                        {
                            Id = 16,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Rumpold"
                        },
                        new
                        {
                            Id = 17,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Fatra"
                        },
                        new
                        {
                            Id = 18,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Gabeo"
                        },
                        new
                        {
                            Id = 19,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "GID"
                        },
                        new
                        {
                            Id = 20,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Neveon"
                        },
                        new
                        {
                            Id = 21,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Gumotex"
                        },
                        new
                        {
                            Id = 22,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "GZR"
                        },
                        new
                        {
                            Id = 23,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Chintex"
                        },
                        new
                        {
                            Id = 24,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Inno Comp"
                        },
                        new
                        {
                            Id = 25,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Repla"
                        },
                        new
                        {
                            Id = 26,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Juta"
                        },
                        new
                        {
                            Id = 27,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Kamiddos"
                        },
                        new
                        {
                            Id = 28,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Kantořík"
                        },
                        new
                        {
                            Id = 29,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Kužílek"
                        },
                        new
                        {
                            Id = 30,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "KV Ekoplast"
                        },
                        new
                        {
                            Id = 31,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Laszlo"
                        },
                        new
                        {
                            Id = 32,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Leifheit"
                        },
                        new
                        {
                            Id = 33,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Magna"
                        },
                        new
                        {
                            Id = 34,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Mondeco"
                        },
                        new
                        {
                            Id = 35,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Nexis"
                        },
                        new
                        {
                            Id = 36,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Oceanize"
                        },
                        new
                        {
                            Id = 37,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "odpo"
                        },
                        new
                        {
                            Id = 38,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Power-Full"
                        },
                        new
                        {
                            Id = 39,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "PFN"
                        },
                        new
                        {
                            Id = 40,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "PlastMetal"
                        },
                        new
                        {
                            Id = 41,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Pošumavská"
                        },
                        new
                        {
                            Id = 42,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Prodos rec"
                        },
                        new
                        {
                            Id = 43,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Rapol"
                        },
                        new
                        {
                            Id = 44,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Regoplast"
                        },
                        new
                        {
                            Id = 45,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Remaq"
                        },
                        new
                        {
                            Id = 46,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Renoplasti"
                        },
                        new
                        {
                            Id = 47,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Reyond"
                        },
                        new
                        {
                            Id = 48,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Silon Recy"
                        },
                        new
                        {
                            Id = 49,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Suchan"
                        },
                        new
                        {
                            Id = 50,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "TKC Kunst"
                        },
                        new
                        {
                            Id = 51,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Torray"
                        },
                        new
                        {
                            Id = 52,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Valek"
                        },
                        new
                        {
                            Id = 53,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Vansida"
                        },
                        new
                        {
                            Id = 54,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Witt and M"
                        },
                        new
                        {
                            Id = 55,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Witte"
                        },
                        new
                        {
                            Id = 56,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "Zeba"
                        },
                        new
                        {
                            Id = 57,
                            Category = "supplier",
                            SortOrder = 0,
                            Value = "ZMPB"
                        },
                        new
                        {
                            Id = 58,
                            Category = "form",
                            SortOrder = 0,
                            Value = "Form"
                        },
                        new
                        {
                            Id = 59,
                            Category = "form",
                            SortOrder = 0,
                            Value = "Regrind"
                        },
                        new
                        {
                            Id = 60,
                            Category = "form",
                            SortOrder = 0,
                            Value = "Scrap"
                        },
                        new
                        {
                            Id = 61,
                            Category = "form",
                            SortOrder = 0,
                            Value = "Regranulate"
                        },
                        new
                        {
                            Id = 62,
                            Category = "form",
                            SortOrder = 0,
                            Value = "Ingots"
                        },
                        new
                        {
                            Id = 63,
                            Category = "form",
                            SortOrder = 0,
                            Value = "Pellets"
                        },
                        new
                        {
                            Id = 64,
                            Category = "form",
                            SortOrder = 0,
                            Value = "Yarn"
                        },
                        new
                        {
                            Id = 65,
                            Category = "form",
                            SortOrder = 0,
                            Value = "Bales"
                        },
                        new
                        {
                            Id = 66,
                            Category = "form",
                            SortOrder = 0,
                            Value = "Lumps"
                        },
                        new
                        {
                            Id = 67,
                            Category = "form",
                            SortOrder = 0,
                            Value = "Rolls"
                        },
                        new
                        {
                            Id = 68,
                            Category = "form",
                            SortOrder = 0,
                            Value = "Other"
                        },
                        new
                        {
                            Id = 69,
                            Category = "form",
                            SortOrder = 0,
                            Value = "Virgin"
                        },
                        new
                        {
                            Id = 70,
                            Category = "filler",
                            SortOrder = 0,
                            Value = "Filler"
                        },
                        new
                        {
                            Id = 71,
                            Category = "filler",
                            SortOrder = 0,
                            Value = "GF"
                        },
                        new
                        {
                            Id = 72,
                            Category = "filler",
                            SortOrder = 0,
                            Value = "TD"
                        },
                        new
                        {
                            Id = 73,
                            Category = "filler",
                            SortOrder = 0,
                            Value = "MD"
                        },
                        new
                        {
                            Id = 74,
                            Category = "filler",
                            SortOrder = 0,
                            Value = "TV"
                        },
                        new
                        {
                            Id = 75,
                            Category = "filler",
                            SortOrder = 0,
                            Value = "CF"
                        },
                        new
                        {
                            Id = 76,
                            Category = "filler",
                            SortOrder = 0,
                            Value = "LGF"
                        },
                        new
                        {
                            Id = 77,
                            Category = "filler",
                            SortOrder = 0,
                            Value = "ESD"
                        },
                        new
                        {
                            Id = 78,
                            Category = "color",
                            SortOrder = 0,
                            Value = "Colour"
                        },
                        new
                        {
                            Id = 79,
                            Category = "color",
                            SortOrder = 0,
                            Value = "Red"
                        },
                        new
                        {
                            Id = 80,
                            Category = "color",
                            SortOrder = 0,
                            Value = "Black"
                        },
                        new
                        {
                            Id = 81,
                            Category = "color",
                            SortOrder = 0,
                            Value = "Blue"
                        },
                        new
                        {
                            Id = 82,
                            Category = "color",
                            SortOrder = 0,
                            Value = "Grey"
                        },
                        new
                        {
                            Id = 83,
                            Category = "material",
                            SortOrder = 0,
                            Value = "PP"
                        },
                        new
                        {
                            Id = 84,
                            Category = "material",
                            SortOrder = 0,
                            Value = "LDPE"
                        },
                        new
                        {
                            Id = 85,
                            Category = "material",
                            SortOrder = 0,
                            Value = "HDPE"
                        },
                        new
                        {
                            Id = 86,
                            Category = "material",
                            SortOrder = 0,
                            Value = "PC/ABS"
                        },
                        new
                        {
                            Id = 87,
                            Category = "material",
                            SortOrder = 0,
                            Value = "PA6"
                        },
                        new
                        {
                            Id = 88,
                            Category = "material",
                            SortOrder = 0,
                            Value = "PA66"
                        });
                });

            modelBuilder.Entity("PhotoApp.Models.PhotoRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalPhotos")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Filler")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Form")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mfi")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MonthlyQuantity")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoFileName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Supplier")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("Photos", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
